import { loadEnvFile, env } from "node:process";
loadEnvFile();

export const APP_NAME = env["APP_NAME"];
export const APP_DEBUG = env["APP_DEBUG"];
export const APP_URL = env["APP_URL"];
export const BASE_URL = env["BASE_URL"];
export const NODE_ENV = env["NODE_ENV"];
export const APP_PORT = env["APP_PORT"];
export const APP_KEEP_ALIVE_TIMEOUT = env["APP_KEEP_ALIVE_TIMEOUT"];
export const APP_HEADERS_TIMEOUT = env["APP_HEADERS_TIMEOUT"];
export const ACCESS_TOKEN_SECRET_KEY = env["ACCESS_TOKEN_SECRET_KEY"];
export const ACCESS_TOKEN_EXPIRATION_TIME = env["ACCESS_TOKEN_EXPIRATION_TIME"];
export const REFRESH_TOKEN_SECRET_KEY = env["REFRESH_TOKEN_SECRET_KEY"];
export const REFRESH_TOKEN_EXPIRATION_TIME = env["REFRESH_TOKEN_EXPIRATION_TIME"];
export const TEMPORARY_TOKEN_SECRET_KEY = env["TEMPORARY_TOKEN_SECRET_KEY"];
export const TEMPORARY_TOKEN_EXPIRATION_TIME = env["TEMPORARY_TOKEN_EXPIRATION_TIME"];
export const UPLOAD_FILE_MAX_SIZE = env["UPLOAD_FILE_MAX_SIZE"];
export const SMTP_USER = env["SMTP_USER"];
export const SMTP_PASS = env["SMTP_PASS"];
export const SMTP_HOST = env["SMTP_HOST"];
export const SMTP_PORT = env["SMTP_PORT"];
export const SMTP_SECURE = env["SMTP_SECURE"];
export const OTP_EXPIRATION_TIME = env["OTP_EXPIRATION_TIME"];
export const PGUSER = env["PGUSER"];
export const PGPASSWORD = env["PGPASSWORD"];
export const PGHOST = env["PGHOST"];
export const PGPORT = env["PGPORT"];
export const PGDATABASE = env["PGDATABASE"];
export const POSTGRES_USER = env["POSTGRES_USER"];
export const POSTGRES_PASSWORD = env["POSTGRES_PASSWORD"];
export const POSTGRES_DB = env["POSTGRES_DB"];
export const STRIPE_PUBLISHABLE_KEY = env["STRIPE_PUBLISHABLE_KEY"];
export const STRIPE_SECRET_KEY = env["STRIPE_SECRET_KEY"];
export const STRIPE_WEBHOOK_SIGNING_SECRET = env["STRIPE_WEBHOOK_SIGNING_SECRET"];
export const CREATE_DATABASE_FILE_PATH = env["CREATE_DATABASE_FILE_PATH"];
export const TRUNCATE_DATABASE_FILE_PATH = env["TRUNCATE_DATABASE_FILE_PATH"];
export const CURRENT_TZ = env["CURRENT_TZ"];