export const ERROR_MESSAGE = "This is an error message"
export const UNAUTHORIZED_MESSAGE = "You are unauthorized to perform this action"
export const SUCCESS_MESSAGE = "Request successful"
export const MISSING_INPUT_FIELDS = "One or more input fields are empty. Please fill up all the input fields before submitting."
export const EMAIL_EXISTS_ALREADY = "Email already exists. Please sign in instead."
export const PASSWORDS_DONT_MATCH = "Passwords don't match. Please try again instead."
